-- H2 内存库建表脚本（unit-test profile）
-- 注：Spring ScriptUtils 不能执行纯注释脚本，故保留一条无害语句占位
SELECT 1;

-- 智能体规格表（spec_code 唯一性由应用层预校验保证——生产库部分唯一索引为 PG 方言，H2 不建）
CREATE TABLE IF NOT EXISTS "ai_agent_spec" (
    "id"            bigint       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name"          varchar(64)  NOT NULL,
    "spec_code"     varchar(64)  NOT NULL,
    "icon"          varchar(128) DEFAULT NULL,
    "owner_level"   varchar(16)  NOT NULL DEFAULT 'TENANT',
    "owner_user_id" bigint       DEFAULT NULL,
    "draft"         text         DEFAULT NULL,
    "current_version_no" int    DEFAULT NULL,
    "creator"       varchar(64)  DEFAULT '',
    "create_time"   datetime     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater"       varchar(64)  DEFAULT '',
    "update_time"   datetime     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    "deleted"       bit          NOT NULL DEFAULT 0,
    "tenant_id"     bigint       NOT NULL DEFAULT 0,
    PRIMARY KEY ("id")
) COMMENT 'AI 平台智能体规格表（行为性配置全在 draft JSON 内，随版本快照固化；主体列只留管理元数据）';

-- 智能体规格版本快照表（不可变：只插不改不删；版本号唯一性由应用层 max+1 计算保证——唯一索引为 PG 方言，H2 不建）
CREATE TABLE IF NOT EXISTS "ai_agent_spec_version" (
    "id"          bigint       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "spec_id"     bigint       NOT NULL,
    "version_no"  int          NOT NULL,
    "config"      text         NOT NULL,
    "note"        varchar(255) DEFAULT NULL,
    "creator"     varchar(64)  DEFAULT '',
    "create_time" datetime     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater"     varchar(64)  DEFAULT '',
    "update_time" datetime     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    "deleted"     bit          NOT NULL DEFAULT 0,
    "tenant_id"   bigint       NOT NULL DEFAULT 0,
    PRIMARY KEY ("id")
) COMMENT 'AI 平台智能体规格版本快照表（不可变：只插不改不删；版本按规格聚合，租户归属继承自规格）';

CREATE TABLE IF NOT EXISTS "ai_channel" (
    "id"         bigint       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name"       varchar(64)  NOT NULL,
    "provider"   varchar(32)  NOT NULL,
    "base_url"   varchar(512) NOT NULL,
    "api_key"    varchar(1024) DEFAULT NULL,
    "enabled"    bit          NOT NULL DEFAULT 1,
    "owner_type" varchar(16)  NOT NULL DEFAULT 'tenant',
    "creator"    varchar(64)  DEFAULT '',
    "create_time" datetime    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater"    varchar(64)  DEFAULT '',
    "update_time" datetime    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    "deleted"    bit          NOT NULL DEFAULT 0,
    "tenant_id"  bigint       NOT NULL DEFAULT 0,
    PRIMARY KEY ("id")
) COMMENT 'AI 平台模型渠道表（api_key 经 EncryptTypeHandler AES 密文落库；归属 MVP 固定 tenant）';

CREATE TABLE IF NOT EXISTS "ai_model" (
    "id"              bigint         NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "channel_id"      bigint         NOT NULL,
    "model_id"        varchar(128)   NOT NULL,
    "name"            varchar(64)    NOT NULL,
    "context_window"  int            DEFAULT NULL,
    "input_price"     decimal(12, 6) DEFAULT NULL,
    "output_price"    decimal(12, 6) DEFAULT NULL,
    "enabled"         bit            NOT NULL DEFAULT 1,
    "creator"         varchar(64)    DEFAULT '',
    "create_time"     datetime       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater"         varchar(64)    DEFAULT '',
    "update_time"     datetime       NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    "deleted"         bit            NOT NULL DEFAULT 0,
    "tenant_id"       bigint         NOT NULL DEFAULT 0,
    PRIMARY KEY ("id")
) COMMENT 'AI 平台模型元数据表（挂接渠道；channel_id+model_id 唯一性由应用层预校验+生产库唯一索引保证）';
