CREATE TABLE IF NOT EXISTS "ai_feedback" (
    "id"             bigint       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "content"        varchar(2048) NOT NULL,
    "screenshot_urls" varchar(4096) DEFAULT NULL,
    "session_id"     varchar(64)   DEFAULT NULL,
    "status"         tinyint       NOT NULL DEFAULT 10,
    "submitter_id"   bigint        NOT NULL,
    "creator"        varchar(64)   DEFAULT '',
    "create_time"    datetime      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater"        varchar(64)   DEFAULT '',
    "update_time"    datetime      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    "deleted"        bit           NOT NULL DEFAULT 0,
    "tenant_id"      bigint        NOT NULL DEFAULT 0,
    PRIMARY KEY ("id")
) COMMENT 'AI 平台问题反馈表';
