-- H2 内存库建表脚本（unit-test profile）
-- 注：Spring ScriptUtils 不能执行纯注释脚本，故保留一条无害语句占位
SELECT 1;

-- 智能体规格表（spec_code 唯一性由应用层预校验保证——生产库部分唯一索引为 PG 方言，H2 不建）
CREATE TABLE IF NOT EXISTS "ai_agent_spec" (
    "id"            bigint       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name"          varchar(64)  NOT NULL,
    "spec_code"     varchar(64)  NOT NULL,
    "icon"          varchar(128) DEFAULT NULL,
    "owner_level"   varchar(16)  NOT NULL DEFAULT 'TENANT',
    "owner_user_id" bigint       DEFAULT NULL,
    "draft"         text         DEFAULT NULL,
    "creator"       varchar(64)  DEFAULT '',
    "create_time"   datetime     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater"       varchar(64)  DEFAULT '',
    "update_time"   datetime     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    "deleted"       bit          NOT NULL DEFAULT 0,
    "tenant_id"     bigint       NOT NULL DEFAULT 0,
    PRIMARY KEY ("id")
) COMMENT 'AI 平台智能体规格表（行为性配置全在 draft JSON 内，随版本快照固化；主体列只留管理元数据）';
